# Generated by Django 5.2.7 on 2025-10-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upcoming',
            field=models.BooleanField(default=False),
        ),
    ]
