name: Deploy Django Backend to EC2

on:
  push:
    branches:
      - main  # triggers when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/Mobilemart_Django_Backend
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python MobileMark_Backend/manage.py migrate
          python MobileMark_Backend/manage.py collectstatic --noinput
          sudo systemctl restart daphne
          sudo systemctl restart nginx
          EOF