# Generated by Django 5.2.7 on 2025-10-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The offer message to display in the banner.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active offers will be shown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
